# Generated by Django 2.2.16 on 2022-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221125_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите подходящую картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
