# Generated by Django 2.2.16 on 2022-11-27 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20221127_1335'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Follow_unique',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
    ]
